-- Config Menu TUI for Nexus
-- Provides a user-friendly floating window to configure Nexus settings
-- Settings are persisted to .nexus/config.lua in the project root

local M = {}

local api = vim.api

-- Available sections with display names
-- allow_infinity: if false, count has a minimum of 1 (no "∞" option)
local SECTIONS = {
  { id = "dashboard_buttons", name = "Dashboard Buttons" },
  { id = "keyboard_shortcuts", name = "Keyboard Shortcuts" },
  { id = "todos", name = "Todos", has_count = true, count_key = "max_todos", default_count = 10, allow_infinity = true },
  { id = "recent_commits", name = "Recent Commits", has_count = true, count_key = "recent_commits_count", default_count = 3, allow_infinity = false },
  { id = "git_status", name = "Git Status", has_count = true, count_key = "git_status_count", default_count = nil, allow_infinity = true },
  { id = "linear_issues", name = "Linear Issues" },
  { id = "huly_issues", name = "Huly Issues" },
  { id = "beads_issues", name = "Beads Issues" },
}

-- Logo options
local LOGOS = { "neovim", "nexus", "project", "image" }

-- Boolean toggles (displayed below sections, above logo)
local TOGGLES = {
  { id = "collapse_untracked", name = "Collapse Untracked", config_key = "collapse_untracked" },
}

-- Menu state
local state = {
  buf = nil,
  win = nil,
  cursor_line = 1,
  sections = {},      -- Current section order with enabled state
  logo_selection = "nexus",
  counts = {},        -- Count values for sections that have them
  toggles = {},       -- Boolean toggle states { id, name, value }
}

-- Get the .nexus config file path
local function get_config_path()
  local git_root = require('nexus.git.root').get()
  if not git_root then
    return nil
  end
  return git_root .. "/.nexus/config.lua"
end

-- Ensure .nexus directory exists
local function ensure_nexus_dir()
  local git_root = require('nexus.git.root').get()
  if not git_root then
    return false
  end
  local nexus_dir = git_root .. "/.nexus"
  if vim.fn.isdirectory(nexus_dir) == 0 then
    vim.fn.mkdir(nexus_dir, "p")
  end
  return true
end

-- Load config from .nexus/config.lua
local function load_persisted_config()
  local config_path = get_config_path()
  if not config_path or vim.fn.filereadable(config_path) == 0 then
    return nil
  end

  local ok, loaded = pcall(dofile, config_path)
  if ok and type(loaded) == "table" then
    return loaded
  end
  return nil
end

-- Save config to .nexus/config.lua
local function save_persisted_config(cfg)
  if not ensure_nexus_dir() then
    vim.notify("Could not create .nexus directory", vim.log.levels.ERROR)
    return false
  end

  local config_path = get_config_path()
  if not config_path then
    vim.notify("Could not determine config path", vim.log.levels.ERROR)
    return false
  end

  -- Build section_order from enabled sections
  local section_order = {}
  for _, section in ipairs(cfg.sections) do
    if section.enabled then
      table.insert(section_order, section.id)
    end
  end

  -- Build the config table
  local lines = {
    "-- Nexus configuration (auto-generated by config menu)",
    "-- Edit via the config menu (press ',' in Nexus buffer)",
    "return {",
    string.format("  logo_selection = %q,", cfg.logo_selection),
    "  section_order = {",
  }

  for _, id in ipairs(section_order) do
    table.insert(lines, string.format("    %q,", id))
  end
  table.insert(lines, "  },")

  -- Add count settings
  for _, section in ipairs(SECTIONS) do
    if section.has_count and cfg.counts[section.count_key] ~= nil then
      local val = cfg.counts[section.count_key]
      if val == nil then
        table.insert(lines, string.format("  %s = nil,", section.count_key))
      else
        table.insert(lines, string.format("  %s = %d,", section.count_key, val))
      end
    end
  end

  -- Add boolean toggle settings
  for _, toggle in ipairs(cfg.toggles or {}) do
    table.insert(lines, string.format("  %s = %s,", toggle.config_key, tostring(toggle.value)))
  end

  table.insert(lines, "}")

  local content = table.concat(lines, "\n")
  local file = io.open(config_path, "w")
  if not file then
    vim.notify("Could not write to " .. config_path, vim.log.levels.ERROR)
    return false
  end
  file:write(content)
  file:close()

  return true
end

-- Initialize state from current config
local function init_state()
  local config = require('nexus.config').get()
  local persisted = load_persisted_config()

  -- Merge persisted config if available
  if persisted then
    config = vim.tbl_deep_extend('force', config, persisted)
  end

  state.logo_selection = config.logo_selection or "nexus"
  state.counts = {}
  state.toggles = {}

  -- Initialize boolean toggles
  for _, t in ipairs(TOGGLES) do
    table.insert(state.toggles, {
      id = t.id,
      name = t.name,
      config_key = t.config_key,
      value = config[t.config_key] or false,
    })
  end

  -- Build sections list with enabled state
  state.sections = {}
  local section_order = config.section_order or {}
  local order_set = {}
  for i, id in ipairs(section_order) do
    order_set[id] = i
  end

  -- First add enabled sections in order
  for _, id in ipairs(section_order) do
    for _, s in ipairs(SECTIONS) do
      if s.id == id then
        table.insert(state.sections, {
          id = s.id,
          name = s.name,
          enabled = true,
          has_count = s.has_count,
          count_key = s.count_key,
          default_count = s.default_count,
          allow_infinity = s.allow_infinity,
        })
        if s.has_count then
          state.counts[s.count_key] = config[s.count_key] or s.default_count
        end
        break
      end
    end
  end

  -- Then add disabled sections
  for _, s in ipairs(SECTIONS) do
    if not order_set[s.id] then
      table.insert(state.sections, {
        id = s.id,
        name = s.name,
        enabled = false,
        has_count = s.has_count,
        count_key = s.count_key,
        default_count = s.default_count,
        allow_infinity = s.allow_infinity,
      })
      if s.has_count then
        state.counts[s.count_key] = config[s.count_key] or s.default_count
      end
    end
  end
end

-- Render the menu content
local function render()
  if not state.buf or not api.nvim_buf_is_valid(state.buf) then
    return
  end

  local lines = {}
  local highlights = {}

  -- Header
  table.insert(lines, "")
  table.insert(lines, "  Sections:")
  table.insert(lines, "")

  -- Sections
  local section_start_line = #lines
  for i, section in ipairs(state.sections) do
    local checkbox = section.enabled and "[✓]" or "[ ]"
    local count_str = ""
    if section.has_count then
      local count = state.counts[section.count_key]
      count_str = count and string.format("  count: %d", count) or "  count: ∞"
    end
    local line = string.format("   %s %s%s", checkbox, section.name, count_str)
    table.insert(lines, line)

    -- Highlight the checkbox
    local hl_group = section.enabled and "DiagnosticOk" or "Comment"
    table.insert(highlights, {
      line = #lines - 1,
      col_start = 3,
      col_end = 6,
      group = hl_group,
    })

    -- Highlight count if present
    if section.has_count then
      local count_start = #line - #count_str + 2
      table.insert(highlights, {
        line = #lines - 1,
        col_start = count_start,
        col_end = #line,
        group = "Number",
      })
    end
  end

  table.insert(lines, "")

  -- Boolean toggles
  local toggle_start_line = #lines
  for i, toggle in ipairs(state.toggles) do
    local checkbox = toggle.value and "[✓]" or "[ ]"
    local line = string.format("   %s %s", checkbox, toggle.name)
    table.insert(lines, line)

    local hl_group = toggle.value and "DiagnosticOk" or "Comment"
    table.insert(highlights, {
      line = #lines - 1,
      col_start = 3,
      col_end = 6,
      group = hl_group,
    })
  end
  state.toggle_start_line = toggle_start_line
  state.toggle_end_line = toggle_start_line + #state.toggles - 1

  table.insert(lines, "")

  -- Logo selection
  local logo_line = #lines
  local logo_str = string.format("  Logo: %s", state.logo_selection)
  table.insert(lines, logo_str)
  table.insert(highlights, {
    line = logo_line,
    col_start = 8,
    col_end = 8 + #state.logo_selection,
    group = "String",
  })

  table.insert(lines, "")
  table.insert(lines, "  ─────────────────────────────────────────")
  table.insert(lines, "")
  table.insert(lines, "  <Space>: Toggle    K/J: Move Up/Down")
  table.insert(lines, "  +/-: Adjust Count  l: Cycle Logo")
  table.insert(lines, "  s: Save & Close    q: Close (no save)")
  table.insert(lines, "")

  -- Store line mapping for cursor positioning
  state.section_start_line = section_start_line
  state.section_end_line = section_start_line + #state.sections - 1
  state.logo_line = logo_line

  -- Set buffer content
  api.nvim_buf_set_option(state.buf, 'modifiable', true)
  api.nvim_buf_set_lines(state.buf, 0, -1, false, lines)
  api.nvim_buf_set_option(state.buf, 'modifiable', false)

  -- Apply highlights
  local ns = api.nvim_create_namespace('nexus_config_menu')
  api.nvim_buf_clear_namespace(state.buf, ns, 0, -1)
  for _, hl in ipairs(highlights) do
    api.nvim_buf_set_extmark(state.buf, ns, hl.line, hl.col_start, { end_col = hl.col_end, hl_group = hl.group })
  end

  -- Highlight current line
  if state.cursor_line >= state.section_start_line and state.cursor_line <= state.section_end_line then
    api.nvim_buf_set_extmark(state.buf, ns, state.cursor_line, 0, { end_row = state.cursor_line + 1, end_col = 0, hl_group = 'CursorLine', strict = false })
  elseif state.toggle_start_line and state.cursor_line >= state.toggle_start_line and state.cursor_line <= state.toggle_end_line then
    api.nvim_buf_set_extmark(state.buf, ns, state.cursor_line, 0, { end_row = state.cursor_line + 1, end_col = 0, hl_group = 'CursorLine', strict = false })
  elseif state.cursor_line == state.logo_line then
    api.nvim_buf_set_extmark(state.buf, ns, state.cursor_line, 0, { end_row = state.cursor_line + 1, end_col = 0, hl_group = 'CursorLine', strict = false })
  end
end

-- Get section index from cursor line
local function get_section_index()
  if state.cursor_line >= state.section_start_line and state.cursor_line <= state.section_end_line then
    return state.cursor_line - state.section_start_line + 1
  end
  return nil
end

-- Get toggle index from cursor line
local function get_toggle_index()
  if state.toggle_start_line and state.cursor_line >= state.toggle_start_line and state.cursor_line <= state.toggle_end_line then
    return state.cursor_line - state.toggle_start_line + 1
  end
  return nil
end

-- Toggle current section or boolean toggle
local function toggle_section()
  -- Check if on a boolean toggle row
  local tidx = get_toggle_index()
  if tidx then
    state.toggles[tidx].value = not state.toggles[tidx].value
    render()
    return
  end
  local idx = get_section_index()
  if idx then
    state.sections[idx].enabled = not state.sections[idx].enabled
    render()
  end
end

-- Move section up
local function move_section_up()
  local idx = get_section_index()
  if idx and idx > 1 then
    state.sections[idx], state.sections[idx - 1] = state.sections[idx - 1], state.sections[idx]
    state.cursor_line = state.cursor_line - 1
    render()
    api.nvim_win_set_cursor(state.win, { state.cursor_line + 1, 0 })
  end
end

-- Move section down
local function move_section_down()
  local idx = get_section_index()
  if idx and idx < #state.sections then
    state.sections[idx], state.sections[idx + 1] = state.sections[idx + 1], state.sections[idx]
    state.cursor_line = state.cursor_line + 1
    render()
    api.nvim_win_set_cursor(state.win, { state.cursor_line + 1, 0 })
  end
end

-- Adjust count for current section
local function adjust_count(delta)
  local idx = get_section_index()
  if idx and state.sections[idx].has_count then
    local key = state.sections[idx].count_key
    local current = state.counts[key]
    local allow_infinity = state.sections[idx].allow_infinity

    if current == nil then
      -- Currently infinite, set to a starting value
      if delta > 0 then
        state.counts[key] = 1
      end
    else
      local new_val = current + delta
      if new_val < 1 then
        if allow_infinity then
          state.counts[key] = nil  -- Set to infinite
        else
          state.counts[key] = 1  -- Minimum of 1 for sections that don't allow infinity
        end
      else
        state.counts[key] = new_val
      end
    end
    render()
  end
end

-- Cycle logo selection
local function cycle_logo()
  if state.cursor_line == state.logo_line then
    local current_idx = 1
    for i, logo in ipairs(LOGOS) do
      if logo == state.logo_selection then
        current_idx = i
        break
      end
    end
    state.logo_selection = LOGOS[(current_idx % #LOGOS) + 1]
    render()
  end
end

-- Navigate cursor
local function move_cursor(direction)
  local new_line = state.cursor_line + direction

  -- Clamp to valid range (sections + toggles + logo)
  if new_line < state.section_start_line then
    new_line = state.section_start_line
  elseif new_line > state.section_end_line and new_line < (state.toggle_start_line or state.logo_line) then
    new_line = direction > 0 and (state.toggle_start_line or state.logo_line) or state.section_end_line
  elseif state.toggle_end_line and new_line > state.toggle_end_line and new_line < state.logo_line then
    new_line = direction > 0 and state.logo_line or state.toggle_end_line
  elseif new_line > state.logo_line then
    new_line = state.logo_line
  end

  state.cursor_line = new_line
  render()
  api.nvim_win_set_cursor(state.win, { state.cursor_line + 1, 0 })
end

-- Save and close
local function save_and_close()
  local cfg = {
    sections = state.sections,
    logo_selection = state.logo_selection,
    counts = state.counts,
    toggles = state.toggles,
  }

  if save_persisted_config(cfg) then
    vim.notify("Nexus config saved to .nexus/config.lua", vim.log.levels.INFO)

    -- Update runtime config
    local config = require('nexus.config')
    local section_order = {}
    for _, section in ipairs(state.sections) do
      if section.enabled then
        table.insert(section_order, section.id)
      end
    end

    local new_config = {
      logo_selection = state.logo_selection,
      section_order = section_order,
    }
    for key, val in pairs(state.counts) do
      new_config[key] = val
    end
    for _, toggle in ipairs(state.toggles) do
      new_config[toggle.config_key] = toggle.value
    end

    config.setup(new_config)
  end

  M.close()

  -- Refresh Nexus buffer
  local nexus = require('nexus')
  for _, buf in ipairs(api.nvim_list_bufs()) do
    if api.nvim_buf_is_valid(buf) then
      if vim.bo[buf].filetype == 'nexus' then
        nexus.refresh_buffer(buf)
        break
      end
    end
  end
end

-- Close without saving
function M.close()
  if state.win and api.nvim_win_is_valid(state.win) then
    api.nvim_win_close(state.win, true)
  end
  if state.buf and api.nvim_buf_is_valid(state.buf) then
    api.nvim_buf_delete(state.buf, { force = true })
  end
  state.win = nil
  state.buf = nil
end

-- Open the config menu
function M.open()
  -- Initialize state from config
  init_state()

  -- Calculate window size
  local width = 45
  local height = #state.sections + #state.toggles + 12
  local ui = api.nvim_list_uis()[1]
  local col = math.floor((ui.width - width) / 2)
  local row = math.floor((ui.height - height) / 2)

  -- Create buffer
  state.buf = api.nvim_create_buf(false, true)
  api.nvim_buf_set_option(state.buf, 'bufhidden', 'wipe')
  api.nvim_buf_set_option(state.buf, 'filetype', 'nexus_config')

  -- Create floating window
  state.win = api.nvim_open_win(state.buf, true, {
    relative = 'editor',
    width = width,
    height = height,
    col = col,
    row = row,
    style = 'minimal',
    border = 'rounded',
    title = ' Nexus Config ',
    title_pos = 'center',
  })

  -- Window options
  api.nvim_win_set_option(state.win, 'cursorline', false)
  api.nvim_win_set_option(state.win, 'wrap', false)

  -- Initial cursor position
  state.cursor_line = 3  -- First section line (0-indexed)

  -- Render content
  render()

  -- Set cursor
  api.nvim_win_set_cursor(state.win, { state.cursor_line + 1, 0 })

  -- Set up keymaps
  local opts = { buffer = state.buf, nowait = true, silent = true }

  vim.keymap.set('n', 'q', M.close, opts)
  vim.keymap.set('n', '<Esc>', M.close, opts)
  vim.keymap.set('n', 's', save_and_close, opts)
  vim.keymap.set('n', '<Space>', toggle_section, opts)
  vim.keymap.set('n', '<CR>', toggle_section, opts)
  vim.keymap.set('n', 'K', move_section_up, opts)
  vim.keymap.set('n', 'J', move_section_down, opts)
  vim.keymap.set('n', 'j', function() move_cursor(1) end, opts)
  vim.keymap.set('n', 'k', function() move_cursor(-1) end, opts)
  vim.keymap.set('n', '+', function() adjust_count(1) end, opts)
  vim.keymap.set('n', '=', function() adjust_count(1) end, opts)
  vim.keymap.set('n', '-', function() adjust_count(-1) end, opts)
  vim.keymap.set('n', 'l', cycle_logo, opts)
  vim.keymap.set('n', '<Tab>', cycle_logo, opts)
end

return M
